// lang-it.ts

export const LANG_IT_NAME = 'it';

export const LANG_IT_TRANS = {
    'accesible': 'accessibile',
    'access information':	'informazioni di accesso',
    'account activated':	'conto attivato',
    'add': 'aggiungere',
    'add city':	'aggiungi città',
    'add country':	'aggiungi paese',
    'add route':	'aggiungi percorso',
    'all fields mandatory':	'tutti i campi sono obbligatori',
    'bikeable': 'ciclabile',
    'catalog': 'catalogo',
    'city name':	'nome della città',
    'confirm email text':	'si prega di confermare la tua email utilizzando il link inviato alla tua casella di posta',
    'confirm email title': 'confermare la tua email',
    'country': 'paese',
    'country name':	'nome del paese',
    'email': 'email',
    'english': 'inglese',
    'error': 'errore',
    'italian': 'italiano',
    'login': 'login',
    'logout': 'uscita',
    'map': 'mappa',
    'no account?':	'non hai un account?',
    'not allowed-text':	'non si dispone di autorizzazioni sufficienti per eseguire questa azione',
    'not allowed-title':	'accesso non autorizzato',
    'open route':	'aprire percorso',
    'password': 'password',
    'route description':	'descrizione del percorso',
    'route location':	'posizione di percorso',
    'route name':	'nome del percorso',
    'route tagline':	'slogan del percorso',
    'routes': 'percorsi',
    'select city':	'seleziona città',
    'select country':	'seleziona paese',
    'signup': 'registrazione',
    'spanish': 'spagnolo',
    'username': 'utente',
    'walkable': 'caminabile',
    'add route points':	'aggiungere punti al percorso',
    'add point':	'aggiungere un nuovo punto',
    'point name':	'nome del punto',
    'save': 'salva',
    'point type':	'tipo di punto',
    'type': 'tipo di punto',
    'historic': 'storico',
    'monument': 'monumento',
    'natural': 'naturale',
    'cultural': 'culturale',
    'point location':	'posizione del punto',
    'latitude': 'latitudine',
    'longitude': 'longitudine',
    'route image': 'immagine del percorso'
};
