// lang-es.ts

export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
    'catalog': 'catálogo',
    'email': 'email',
    'password': 'password',
    'db-error': 'database error',
    'city-missingInfo': 'you must fill the name and countryId',
    'user-notAllowed': 'user not allowed to perform this action',
    'city-saveSuccess': 'the city was saved successfully',
    'city-modifySuccess': 'the city was modified successfully',
    'city-deleteSuccess': 'the city was deleted successfully',
    'image-deleteError': 'there was an error deleting the image',
    'image-deleteSuccess': 'the image was deleted successfully',
    'country-missingInfo': 'missing information',
    'country-saveSuccess': 'the country was saved successfully',
    'route-missingInfo': 'missing information',
    'route-idError': 'the route was not found',
    'route-saveSuccess': 'the route was saved successfully',
    'route-modifySuccess': 'the route was modified successfully',
    'route-deleteSuccess': 'the route was deleted successfully',
    'comment-missingInfo': 'missing information',
    'comment-saveSuccess': 'the comment was saved successfully',
    'comment-modifySuccess': 'the comment was modified successfully',
    'comment-deleteSuccess': 'the comment was deleted successfully',
    'country-noRoutesFound': 'no routes found in that country',
    'city-noRoutesFound': 'no routes found in that city',
    'route-noCommentsFound': 'no comments found for that route',
    'route-noImagesFound': 'no images found for that route',
    'images-nameError': 'name error',
    'images-uploadSuccess': 'images uploaded successfully',
    'images-deleteSuccess': 'images deleted successfully',
    'access-appTokenError': 'app token error',
    'access-missingInfo': 'missing information',
    'access-notValidEmail': 'not valid email',
    'access-notValidToken': 'not valid token',
    'access-mailSuccess': 'an email was sent successfully',
    'access-activateSuccess': 'user activated successfully',
    'login-missingInfo': 'missing email or password',
    'login-userNotFound': 'user not found',
    'login-userNotActive': 'user not active',
    'login-wrongInfo': 'wrong email or password',
    'user-noCommentsFound': 'no comments found for that user',
    'user-modifySuccess': 'user modified successfully',
    'user-disableSuccess': 'user disabled successfully',
    'unknown-error': 'something went wrong',
    'confirm email title': 'confirm your email',
    'confirm email text': 'please confirm your email account by clicking the link we have sent to your inbox',
    'accessible':    'accesible',
    'access information': 'información de acceso',
    'account activated': 'cuenta activada',
    'add': 'añadir',
    'add city': 'añadir ciudad',
    'add country': 'añadir país',
    'add route': 'añadir ruta',
    'all fields mandatory': 'todos los campos son obligatorios',
    'bikeable': 'ciclable',
    'city name': 'nombre de la ciudad',
    'country': 'país',
    'country name': 'nombre del país',
    'english': 'inglés',
    'error': 'error',
    'italian': 'italiano',
    'login': 'login',
    'logout': 'salir',
    'map': 'mapa',
    'no account?': '¿no tienes cuenta?',
    'not allowed-text': 'no tiene permisos suficientes para realizar esta acción',
    'not allowed-title ':   'acceso no permitido',
    'open route': 'abrir ruta',
    'route description':   'descripción de la ruta',
    'route location': 'ubicación de la ruta',
    'route name': 'nombre de la ruta',
    'route tagline': 'eslogan de la ruta',
    'routes': 'rutas',
    'select city': 'seleccionar ciudad' ,
    'select country': 'seleccionar país',
    'signup': 'registro',
    'spanish': 'español',
    'username': 'usuario',
    'walkable': 'caminable',
    'add route points': 'añadir puntos de la ruta',
    'add point': 'añadir nuevo punto',
    'point name': 'nombre del punto',
    'save': 'guardar',
    'point type': 'tipo de punto',
    'type': 'tipo',
    'historic': 'histórico',
    'monument': 'monumento',
    'natural': 'natural',
    'cultural': 'cultural',
    'point location': 'ubicación del punto',
    'latitude': 'latitud',
    'longitude': 'longitud',
    'route image': 'imagen de la ruta'
};
