// 'lang-en':.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'catalog': 'catalog',
    'email': 'email',
    'login': 'login',
    'map': 'map',
    'no account?': 'don\'t you have an account?',
    'password': 'password',
    'signup': 'signup',
    'username': 'username',
    'db-error': 'database error',
    'city-missingInfo': 'you must fill the name and countryId',
    'user-notAllowed': 'user not allowed to perform this action',
    'city-saveSuccess': 'the city was saved successfully',
    'city-modifySuccess': 'the city was modified successfully',
    'city-deleteSuccess': 'the city was deleted successfully',
    'image-deleteError': 'there was an error deleting the image',
    'image-deleteSuccess': 'the image was deleted successfully',
    'country-missingInfo': 'missing information',
    'country-saveSuccess': 'the country was saved successfully',
    'route-missingInfo': 'missing information',
    'route-idError': 'the route was not found',
    'route-saveSuccess': 'the route was saved successfully',
    'route-modifySuccess': 'the route was modified successfully',
    'route-deleteSuccess': 'the route was deleted successfully',
    'comment-missingInfo': 'missing information',
    'comment-saveSuccess': 'the comment was saved successfully',
    'comment-modifySuccess': 'the comment was modified successfully',
    'comment-deleteSuccess': 'the comment was deleted successfully',
    'country-noRoutesFound': 'no routes found in that country',
    'city-noRoutesFound': 'no routes found in that city',
    'route-noCommentsFound': 'no comments found for that route',
    'route-noImagesFound': 'no images found for that route',
    'images-nameError': 'name error',
    'images-uploadSuccess': 'images uploaded successfully',
    'images-deleteSuccess': 'images deleted successfully',
    'access-appTokenError': 'app token error',
    'access-missingInfo': 'missing information',
    'access-notValidEmail': 'not valid email',
    'access-notValidToken': 'not valid token',
    'access-mailSuccess': 'an email was sent successfully',
    'access-activateSuccess': 'user activated successfully',
    'login-missingInfo': 'missing email or password',
    'login-userNotFound': 'user not found',
    'login-userNotActive': 'user not active',
    'login-wrongInfo': 'wrong email or password',
    'user-noCommentsFound': 'no comments found for that user',
    'user-modifySuccess': 'user modified successfully',
    'user-disableSuccess': 'user disabled successfully',
    'accesible':    'accessible',
    'access information':    'access information',
    'account activated':    'account activated',
    'add': 'add',
    'add city': 'add city',
    'add country': 'add country',
    'add route': 'add route',
    'all fields mandatory':    'all fields are mandatory',
    'bikeable':    'cyclable',
    'city name':    'city name',
    'confirm email text':    'please, confirm your email using the link that has been sent to your inbox',
    'confirm email title':    'confirm your email',
    'country':    'country',
    'country name':    'country name',
    'english':    'english',
    'error':    'error',
    'italian':    'italian',
    'logout':    'logout',
    'not allowed-text':    'you don\'t have permission to fulfill this action',
    'not allowed-title':   'access not allowed' ,
    'open route':    'open route',
    'route description':    'route description',
    'route location':    'route location',
    'route name':    'route name',
    'route tagline':    'route tagline',
    'routes':    'routes',
    'select city':    'select city',
    'select country':    'select country',
    'spanish':    'spanish',
    'walkable':    'walkable',
    'add route points':    'add route points',
    'add point':    'add new point',
    'point name':    'point name',
    'save':    'save',
    'point type':    'point type',
    'type':    'type',
    'historic':    'historical',
    'monument':    'monument',
    'natural':    'natural',
    'cultural':    'cultural',
    'point location':    'point location',
    'latitude':    'latitude',
    'longitude':    'longitude'

};
